version: 2

jobs:
  rustfmt:
    docker:
      - image: "circleci/rust:1.43"
    steps:
      - checkout
      - run:
          name: install rustfmt
          command: rustup component add rustfmt
      - run:
          name: run rustfmt
          command: cargo fmt -- --check

  clippy:
    docker:
      - image: "circleci/rust:1.43"
    steps:
      - checkout
      - run:
          name: install clippy
          command: rustup component add clippy
      - run:
          name: run clippy
          command: cargo clippy

  test:
    docker:
      - image: "circleci/rust:1.43"
    steps:
      - checkout
      - run:
          name: Install tarpaulin
          command: cargo install cargo-tarpaulin
      - run:
          name: build project
          command: cargo build
      - run:
          name: run tests
          command: cargo tarpaulin
      - run:
          name: Upload to codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  trello_test:
    jobs:
      - clippy
      - rustfmt
      - test
